import { Button, VerticalBox , LineEdit} from "std-widgets.slint";

component CalculateButton {
    callback clicked();
    Button {
        text: "calculate";
        primary: true;
        height: 35px;
        clicked => {clicked()}
    }

}

export component AppWindow inherits Window {
    in property <string> results: "";
    in-out property <bool> open-curtain;
    callback request-divide-income(string);

    GridLayout {
        padding: 50px;
        spacing: 25px;
        Row {
            Text {
                text: "Enter Total Income";
                horizontal-alignment: center;
                font-size: 24px;
                font-weight: 900;
            }
        }
        Row {
            income := LineEdit {
                horizontal-alignment: center;
                font-size: 16px;
                placeholder-text: "Text Here";
                height: 35px;
            }
        }
        Row {
            CalculateButton {
                clicked => {
                    root.open-curtain = !root.open-curtain;
                    request-divide-income(income.text);
                }
            }
        }

        Row {
            VerticalBox {
                Rectangle {
                    height: 100px;
                    background: #f2f2f2;
                    Text {
                        color: black;
                        text: root.results;
                        font-size: 16px;
                        font-weight: 500;
                    }

                    Rectangle {
                        background: #333333;
                        x: 0;
                        width: open-curtain ? 0px : parent.width / 2;
                        height: parent.height;
                        animate width {
                            duration: 250ms;
                            easing: ease-in;
                        }
                    }
                    Rectangle {
                        background: #333333;
                        x: open-curtain ? parent.width : parent.width / 2;
                        width: open-curtain ? 0px : parent.width / 2;
                        animate width {
                            duration: 250ms;
                            easing: ease-in;
                        }
                        animate x {
                            duration: 250ms;
                            easing: ease-in;
                        }
                    }
                }
            }
        }
    }
}
