import { Button, VerticalBox , LineEdit} from "std-widgets.slint";

component CalculateButton {
    callback clicked();
    Button {
        text: "calculate";
        primary: true;
        height: 35px;
        clicked => {clicked()}
    }

}

export component AppWindow inherits Window {
    in property <string> results: "";
    callback request-divide-income(string);

    GridLayout {
        padding: 50px;
        spacing: 25px;
        Row {
            Text {
                text: "Enter Total Income";
                horizontal-alignment: center;
                font-size: 24px;
                font-weight: 900;
            }
        }
        Row {
            income := LineEdit {
                horizontal-alignment: center;
                font-size: 16px;
                placeholder-text: "Text Here";
                height: 35px;
            }
        }
        Row {
            CalculateButton {
                clicked => {request-divide-income(income.text)}
            }
        }

        Row {
            VerticalBox {
                Rectangle {
                    height: 100px;
                    background: #f2f2f2;
                    Text {
                        color: black;
                        text: root.results;
                        font-size: 16px;
                        font-weight: 500;
                    }
                }
            }
        }
    }
}
